#!/usr/bin/env bash

DMEDITOR="vim"

declare -a options=(
"bash - $HOME/.bashrc"
"bspwm - $HOME/.config/bspwm/bspwmrc"
"dmenu - $HOME/.config/dmenu/config.h"
"picom - $HOME/.config/picom/"
"polybar - $HOME/.config/polybar/config"
"qtile - $HOME/.config/qtile/config.py"
"sxhkd - $HOME/.config/sxhkd/sxhkdrc"
"vim - $HOME/.vimrc"
"xresources - $HOME/.Xresources"
"quit"
)

choice=$(printf '%s\n' "${options[@]}" | dmenu -l 20 -p 'Edit config:')

if [[ "$choice" == "quit" ]]; then
	echo "Program terminated." && exit 1

elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	$DMEDITOR "$cfg"

else
	echo "Program terminated." && exit 1
fi
